### ISSUE TITLE
Partition databases between CPU cores

### ISSUE THREAD

**Issue by penberg** [penberg/hiisi#1]
We already have the infrastructure for thread-per core, but we still need partition databases by core and steer requests to the right partition.

**Comment by numinnex** [comment]
I have experience with building thread per core mesh shard using `monoio`, by looking at the commit history you've initially went with `monoio` as your runtime of choice, might I ask why you decided to ditch it and go for the `tigerbeetle` inspired I/O loop ? Is it because of the simulator ?

**Comment by penberg** [comment]
Yes, wanted to go for TigerBeetle style approach for deterministic simulation testing.
